import { vi } from 'vitest';
import type { AppInterface, CrmContact, CrmNote, MailMessage } from '../types';

const crmDefaults = {
  crmContacts: [] as CrmContact[],
  crmSearch: '',
  crmColorFilter: { green: true, yellow: true, red: true },
  crmSelectedContact: null as CrmContact | null,
  crmNotes: [] as CrmNote[],
  setCrmContacts: vi.fn(),
  setCrmSearch: vi.fn(),
  setCrmColorFilter: vi.fn(),
  setCrmSelectedContact: vi.fn(),
  setCrmNotes: vi.fn(),
  crmAddContact: vi.fn(),
  crmUpdateContact: vi.fn(),
  crmDeleteContact: vi.fn(),
  crmIncrementColor: vi.fn(),
  crmAddNote: vi.fn(),
  crmDeleteNote: vi.fn(),
  crmLoadNotes: vi.fn(),
};

const mailDefaults = {
  mailMessages: [] as MailMessage[],
  setMailMessages: vi.fn(),
  mailSend: vi.fn(),
  mailDelete: vi.fn(),
  mailLoad: vi.fn(),
};

export const createMockI = (overrides?: Partial<AppInterface>): AppInterface => ({
  theme: 'dark',
  menuCollapsed: true,
  mode: 'contacts',
  search: '',
  contacts: [],
  currentContact: null,
  searchContact: null,
  feedPosts: [],
  wallPosts: [],
  bulletin: [],
  identity: { web10: 'test/user', name: 'Test', pic: '', bio: '' },
  draftIdentity: { web10: 'test/user', name: 'Test', pic: '', bio: '' },
  currentMessages: [],
  selectedMessages: [],
  typingIndicator: '',
  setTheme: vi.fn(),
  setMenuCollapsed: vi.fn(),
  setContacts: vi.fn(),
  setCurrentContact: vi.fn(),
  setSearchContact: vi.fn(),
  setFeedPosts: vi.fn(),
  setWallPosts: vi.fn(),
  setBulletin: vi.fn(),
  setIdentity: vi.fn(),
  setDraftIdentity: vi.fn(),
  setCurrentMessages: vi.fn(),
  setSelectedMessages: vi.fn(),
  setTypingIndicator: vi.fn(),
  login: vi.fn(),
  logout: vi.fn(),
  runSearch: vi.fn(),
  getPosts: vi.fn(),
  getContact: vi.fn(),
  isMe: vi.fn(),
  savePostChanges: vi.fn(),
  deletePost: vi.fn(),
  createPost: vi.fn(),
  addContact: vi.fn(),
  deleteCurrentContact: vi.fn(),
  cancelIdentityChanges: vi.fn(),
  saveIdentityChanges: vi.fn(),
  deleteBulletin: vi.fn(),
  getMessages: vi.fn(),
  chat: vi.fn(),
  selectMessage: vi.fn(),
  deSelectMessage: vi.fn(),
  deleteSelectedMessages: vi.fn(),
  resetSelectedMessages: vi.fn(),
  sendMessage: vi.fn(),
  setMode: vi.fn(),
  toggleMenuCollapsed: vi.fn(),
  toggleTheme: vi.fn(),
  ...crmDefaults,
  ...mailDefaults,
  ...overrides,
});
