name: js-ci

on:
  pull_request:
    paths:
      - ui/**
      - sdk/**
      - marketing/web10-social/**
      - marketing/marketing-ui/**
      - mobile/encryptor/**
      - api/rtc/**
      - .github/workflows/js-ci.yml
      - .github/workflows/js.yml

concurrency:
  group: js-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui:
    uses: ./.github/workflows/js.yml
    with:
      package: ui

  sdk:
    uses: ./.github/workflows/js.yml
    with:
      package: sdk

  web10-social:
    uses: ./.github/workflows/js.yml
    with:
      package: marketing/web10-social

  marketing-ui:
    uses: ./.github/workflows/js.yml
    with:
      package: marketing/marketing-ui

  encryptor:
    uses: ./.github/workflows/js.yml
    with:
      package: mobile/encryptor

  rtc:
    uses: ./.github/workflows/js.yml
    with:
      package: api/rtc
      tests: false
